### PR TITLE
Add birthday field

### LINKED ISSUE #22: As a user, I want to add a birthday for my contacts
...so that I can remember them

### PR DESCRIPTION
**Pull request by vsamarth**
There are some things I (or we, as we will encounter it more and more), have to figure out.
The main problem is how do we conditionally render a field, when there is no value there. Would love suggestions.

Closes #22

### CODE REVIEW

**Comment by gremmyz** [comment]
@vsamarth For conditional rendering, perhaps we could attach a boolean to each component, and only render it if the value is True? Seems like we could do it with JavaFX: [here](https://stackoverflow.com/questions/19666982/is-there-a-way-to-implement-a-property-like-rendered-on-javafx).

**Review by gremmyz — CHANGES_REQUESTED** [review]
Edit command wasn't working properly, adding the suggested code should fix it. Other than that, LGTM!

**Comment by vsamarth** [comment]
Yeah, I forgot about having to store it as well. Will fix it today...

**Review by gremmyz — APPROVED** [review]
Storage looks good, after it passes the tests and checkstyle fixes, LGTM!

**Pull request merged**
