### PR TITLE
Added support for optional fields

### LINKED ISSUE #15: As a user, I want to be able to add a new contact without adding their email
...so that I can add people when I don’t know their email id.

### PR DESCRIPTION
**Pull request by gremmyz**
The fields for phone, email and address are now optional. Fixes #15 #16 #65

**To be done:**
- UI optimization: currently, empty optional fields take up a lot of space. We need to conditionally render the UI.

### CODE REVIEW

**Comment by Lava-Iris** [comment]
I think we can merge this after merging the birthday one?

**Comment by gremmyz** [comment]
> I think we can merge this after merging the birthday one?

Not sure but probably can merge now, since it merges with @vsamarth's branch and not with master. What do you guys think?

**Review by vsamarth — COMMENTED** [review]
@gremmyz I think this allows the individual classes to have an `Empty` value and we still need to make modifications to the `Person` class to incorporate all these optional fields.

What I was thinking of was using something like `PersonBuilder` as @salty-flower suggested in #61 and storing these fields as [`Optional<...>`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) so that we explicitly have to handle the case when there is a missing value,  making it less error prone.

**Comment by gremmyz** [comment]
> @gremmyz I think this allows the individual classes to have an `Empty` value and we still need to make modifications to the `Person` class to incorporate all these optional fields.
> 
> What I was thinking of was using something like `PersonBuilder` as @salty-flower suggested in #61 and storing these fields as [`Optional<...>`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) so that we explicitly have to handle the case when there is a missing value, making it less error prone.

Makes sense, I'll work on the update after your merge?

**Pull request closed without merging**
