### PR TITLE
Revert `chat` description

### LINKED ISSUE #194: [PE-D][Tester E] Unclear documentation for Sending Chats to a contact
User Guide for Sending Chats to a Contact seems a bit unclear.\
From the documentation, it is phrased to seem as though the message would be sent on behalf of the user after the user inputs the command prompt, but the message is just placed into the text box instead.

I feel that this should be made clear to the user, not just through the image.

I also feel that the user should be informed that any pre-existing text in the chat box of the application will be replaced.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: joytqt-1202/ped#5

### PR DESCRIPTION
**Pull request by salty-flower**
...to pre-filled message

Closes #194

### CODE REVIEW

**Comment by Saha9616** [comment]
would you like to add a disclaimer that if a message is orginally present it will be replaced with the new message? apart from that looks good to me

**Comment by gremmyz** [comment]
> would you like to add a disclaimer that if a message is orginally present it will be replaced with the new message? apart from that looks good to me

second this, think its good to have

**Comment by salty-flower** [comment]
> > would you like to add a disclaimer that if a message is orginally present it will be replaced with the new message? apart from that looks good to me
> 
> second this, think its good to have

noted

**Review by gremmyz — APPROVED** [review]
LGTM!

**Pull request merged**
