### PR TITLE
fix bug in search where 'instagram', 'telegram' and 'whatsapp' are considered part of contact by search

### LINKED ISSUE #191: [PE-D][Tester C] Searching "l"
searching for "l" returns the full contact list even when they do not contain "l"

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: bryansendeavour/ped#7

### PR DESCRIPTION
**Pull request by Lava-Iris**
closes #191

### CODE REVIEW

**Review by gremmyz — CHANGES_REQUESTED** [review]
fix didn't seem to work for me, not sure but i think email and birthday may be causing the same issue?

**Comment by Lava-Iris** [comment]
> fix didn't seem to work for me, not sure but i think email and birthday may be causing the same issue?

Can you give an example of a case that doesn't work?

**Comment by gremmyz** [comment]
> Can you give an example of a case that doesn't work?

same case, `search i`

**Comment by Lava-Iris** [comment]
can you try again?

**Review by gremmyz — APPROVED** [review]
Working as intended 👍🏼

**Pull request merged**
